language: c++
group: travis_latest

os:
  - linux
  - osx
  - windows
  language: sh
 
addons:
  apt:
    packages:
      - octave
      
before_install: 
  - if [ "$TRAVIS_OS_NAME" == "osx"]; then brew install octave > /dev/null ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"]; then choco install octave.portable ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux"]; then sudo bash ./before_install_linux.sh ; fi
  
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux"]; then ulimit -c unlimited -S ; fi
  
  
after_failure:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux"]; then
      COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
      gdb -c "$COREFILE" -ex "thread apply all bt" -ex "set pagination 0" -batch /usr/bin/octave-cli # print stack trace
      tail runtests.log
    fi
    
script:
  - travis_wait 45 ./runtests.sh octave-cli

#notifications:
#    slack: e0404:u5tBXbO6D1mEwzJuFZV0MmqJ
